# Generated by Django 4.1.1 on 2022-09-29 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('Id_Medico', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NomM', models.CharField(max_length=50)),
                ('ApeM', models.CharField(max_length=50)),
                ('TelM', models.BigIntegerField()),
                ('Especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NomP', models.CharField(max_length=50)),
                ('ApeP', models.CharField(max_length=50)),
                ('FechaNto', models.DateField()),
                ('Edad', models.IntegerField()),
                ('TelP', models.BigIntegerField()),
                ('Direccion', models.CharField(max_length=50)),
                ('Contacto', models.CharField(max_length=50)),
                ('Parentezco', models.CharField(max_length=50)),
                ('TelC', models.BigIntegerField()),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediplusApp.medicos')),
            ],
        ),
    ]
